In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Boston Housing Dataset

In [15]:
df = pd.read_csv('Boston_housing.csv')

In [16]:
df.head()

,crime_rate,residential_land_zone,non_retail_industry_area,near_river,nitric_oxide_level,avg_rooms,old_house_ratio,distance_to_jobs,highway_accessibility,property_tax_rate,student_teacher_ratio,black_population_index,lower_status_percentage,median_house_price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   crime_rate                506 non-null    float64
 1   residential_land_zone     506 non-null    float64
 2   non_retail_industry_area  506 non-null    float64
 3   near_river                506 non-null    int64
 4   nitric_oxide_level        506 non-null    float64
 5   avg_rooms                 506 non-null    float64
 6   old_house_ratio           506 non-null    float64
 7   distance_to_jobs          506 non-null    float64
 8   highway_accessibility     506 non-null    int64
 9   property_tax_rate         506 non-null    float64
 10  student_teacher_ratio     506 non-null    float64
 11  black_population_index    506 non-null    float64
 12  lower_status_percentage   506 non-null    float64
 13  median_house_price        506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

#### Model traning

In [23]:
x = df.drop('median_house_price',axis=1)
y = df['median_house_price']

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [26]:
from sklearn.preprocessing import StandardScaler
scaller = StandardScaler()
x_train = scaller.fit_transform(x_train)
x_test = scaller.transform(x_test)

In [28]:
from sklearn.svm import SVR
model = SVR()
model.fit(x_train,y_train)

SVR()

In [31]:
y_pred=model.predict(x_test)
y_pred

array([25.82315299, 28.17693827, 17.7161634 , 23.14296836, 16.51090785,
       21.28497452, 17.37600609, 15.86097211, 19.95404583, 19.29253092,
       21.48994929, 19.3634131 , 18.05552675, 21.51824434, 17.73353193,
       22.21490437, 18.98285545, 11.04189286, 33.63012572, 15.12623119,
       25.490071  , 28.06728468, 14.60299873, 22.78027212, 15.56638198,
       15.16259324, 21.53830849, 13.55673097, 21.27023832, 18.67936787,
       19.26489564, 24.09790348, 18.82514582, 18.71143863, 14.70704022,
       17.67936074, 30.77971954, 19.97319772, 22.92267351, 23.74254583,
       15.71226477, 29.17994179, 32.20610587, 18.23129436, 25.38430811,
       15.4114614 , 15.2240495 , 24.72180694, 18.31589132, 29.45262878,
       20.71595616, 32.35352133, 16.76840366, 24.53725853, 36.01843022,
       22.32806238, 16.27714004, 28.56418213, 24.14528472, 15.89186303,
       24.26470723, 27.80003442, 28.57734738, 18.61657268, 22.85183589,
       19.2692639 , 16.18373339, 24.69665004, 27.89798254, 13.59609109,
       20.36837674, 23.39376448, 10.76093156, 20.39159341, 22.47876525,
       13.76589594, 19.34148111, 32.11479323, 14.11239666, 15.51434055,
       20.49182808, 12.04272333, 21.06312816, 11.84317724, 20.19944649,
       26.73892989, 16.20776792, 24.66767755, 25.3816329 , 18.97899647,
       23.80337742, 12.0574135 , 19.28063206, 18.27197948, 20.20505734,
       19.71136709, 19.46489767, 15.08737835, 12.93712916, 13.20107205,
       21.38684465, 23.37527851, 11.66512568, 19.45905761, 22.88893377,
       13.05632832, 18.0852975 , 25.08124502, 21.31094013, 23.59839125,
       11.9551425 , 14.0228654 , 22.54417791, 24.05993033, 30.88328053,
       13.52056924, 32.95862713, 15.2110315 , 20.18629665, 27.0936144 ,
       16.35559741, 24.82391843, 19.97725799, 21.35048852, 24.09331052,
       21.59756493, 24.41984836])

In [32]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6381285303398285
2.7739006477732326

In [34]:
from sklearn.model_selection import GridSearchCV
 
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}


grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)
 
# fitting the model for grid search
grid.fit(x_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.026 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.066 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.017 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.018 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.017 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.189 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.102 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.163 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.156 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.177 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.161 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.079 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.157 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.115 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.138 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.027 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.065 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.024 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.019 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.0001, kernel=rbf;, score=0.003 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.095 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.003 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.0001, kernel=rbf;, score=-0.003 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.178 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.100 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.165 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.178 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.162 total time=   0.0s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.605 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.561 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.582 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.642 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.590 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.548 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.476 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.532 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.558 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.484 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.204 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.129 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.204 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.160 total time=   0.0s
[CV 5/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.173 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.028 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.064 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.025 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.0001, kernel=rbf;, score=-0.018 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.0001, kernel=rbf;, score=0.019 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.559 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.456 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.529 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.640 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.514 total time=   0.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.807 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.793 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.815 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.889 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.819 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.788 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.715 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.789 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.833 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.706 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.574 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.527 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.560 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.592 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.502 total time=   0.0s
[CV 1/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.209 total time=   0.0s
[CV 2/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.135 total time=   0.0s
[CV 3/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.209 total time=   0.0s
[CV 4/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.165 total time=   0.0s
[CV 5/5] END ....C=10, gamma=0.0001, kernel=rbf;, score=0.177 total time=   0.0s
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.643 total time=   0.0s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.546 total time=   0.0s
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.593 total time=   0.0s
[CV 4/5] END ........C=100, gamma=1, kernel=rbf;, score=0.772 total time=   0.0s
[CV 5/5] END ........C=100, gamma=1, kernel=rbf;, score=0.621 total time=   0.0s
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.874 total time=   0.0s
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.848 total time=   0.0s
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.878 total time=   0.0s
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.935 total time=   0.0s
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.880 total time=   0.0s
[CV 1/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.851 total time=   0.0s
[CV 2/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.781 total time=   0.0s
[CV 3/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.883 total time=   0.0s
[CV 4/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.893 total time=   0.0s
[CV 5/5] END .....C=100, gamma=0.01, kernel=rbf;, score=0.781 total time=   0.0s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.755 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.641 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.706 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.789 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.645 total time=   0.0s
[CV 1/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.576 total time=   0.0s
[CV 2/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.532 total time=   0.0s
[CV 3/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.562 total time=   0.0s
[CV 4/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.596 total time=   0.0s
[CV 5/5] END ...C=100, gamma=0.0001, kernel=rbf;, score=0.503 total time=   0.0s
[CV 1/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.643 total time=   0.0s
[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.546 total time=   0.0s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.593 total time=   0.0s
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.772 total time=   0.0s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.621 total time=   0.0s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.802 total time=   0.1s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.868 total time=   0.1s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.827 total time=   0.1s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.900 total time=   0.1s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.863 total time=   0.1s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.863 total time=   0.0s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.738 total time=   0.0s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.923 total time=   0.0s
[CV 4/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.929 total time=   0.0s
[CV 5/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.856 total time=   0.0s
[CV 1/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.820 total time=   0.0s
[CV 2/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.821 total time=   0.0s
[CV 4/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.850 total time=   0.0s
[CV 5/5] END ...C=1000, gamma=0.001, kernel=rbf;, score=0.727 total time=   0.0s
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.742 total time=   0.0s
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.622 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.677 total time=   0.0s
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.768 total time=   0.0s
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.630 total time=   0.0s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [35]:
print(grid.best_params_)
print(grid.best_estimator_)
grid_prediction=grid.predict(x_test)
print(f'\ngrid prediction {grid_prediction}\n')
print("Train:", grid.score(x_train, y_train))
print("Test:", grid.score(x_test, y_test))
best_model = grid.best_estimator_
best_model

{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}
SVR(C=100, gamma=0.1)

grid prediction [26.22268309 31.94938687 14.95297183 21.22732998 16.40701717 22.03473189
 19.36280761 15.8935174  21.94666655 19.63101382 19.09208663 18.97846841
 18.81026812 23.32789312 18.0240228  23.71784589 19.84515228  9.74394685
 46.76267603 13.6504683  23.12990927 26.31195771 12.89439224 25.10095373
 16.0656383  16.26653303 22.22420644 12.50421837 18.69327393 19.01473082
 24.30458966 23.55283812 24.31111923 28.01490747 14.99319781 17.81373616
 32.33874628 19.0003885  22.41932122 22.63395092 17.50215622 29.00538857
 49.52991155 20.36343548 23.96649627 15.33085037 14.18355222 23.41455117
 18.85663074 26.2736692  20.85225784 35.92472144 17.21311452 23.99121076
 46.65266354 22.43074165 15.88038512 32.58222764 23.66154747 17.50246348
 25.51244863 32.02943409 30.06799764 20.32164649 23.09803091 18.5756118
 14.11626313 23.832987   27.58088088 15.84514576 20.81571403 24.8166574
 10.52320802 18.96997291 23.504109    6.4214099  19.55612588 48.01081086
 12.78551238  9.87363873 21.49990229 10.4132002  18.8974582  10.99436827
 20.02044507 28.3168317  15.36679964 24.20141822 22.18476531 18.62461829
 23.05534042 10.27892688 19.42912448 17.75466721 35.25434205 19.92496656
 25.9215581  12.19086894 12.09448902 10.64233243 21.62497647 24.39382656
  8.60987799 19.66345884 21.43695631 10.34389875 17.80153358 23.9794546
 20.02489483 22.36717178 10.2611976  18.26927079 22.23438083 27.74795433
 31.48407881 15.75010865 43.71558005 13.46621405 19.90641755 26.04712552
 19.7598942  24.84236491 19.60319169 19.15989154 21.35581485 20.79933382
 24.74534886]

Train: 0.9805208098837067
Test: 0.8006822055249074

SVR(C=100, gamma=0.1)

In [36]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,grid_prediction))
print(mean_absolute_error(y_test,grid_prediction))

0.8006822055249074
2.3288373985841564

---

#### Predict new values

In [42]:
x.head()

,crime_rate,residential_land_zone,non_retail_industry_area,near_river,nitric_oxide_level,avg_rooms,old_house_ratio,distance_to_jobs,highway_accessibility,property_tax_rate,student_teacher_ratio,black_population_index,lower_status_percentage
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [38]:
import pickle

with open("regression_model.pkl", "wb") as f:
    pickle.dump({
        "model": best_model,
        "scaler": scaller,
    }, f)